<?php

require_once dirname(__FILE__) . '/../../../../../Scorpio/Sco/Array/Helper.php';

/**
 * Test class for Sco_Array_Helper.
 * Generated by PHPUnit on 2012-06-30 at 09:12:56.
 */
class Sco_Array_HelperTest extends PHPUnit_Framework_TestCase
{

	/**
	 * @var Sco_Array_Helper
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new Sco_Array_Helper;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{

	}

	/**
	 * Generated from @assert (array(0, 1, 2, 3, 4, 5), 3) == 3.
	 *
	 * @covers Sco_Array_Helper::seek
	 */
	public function testSeek()
	{
		$this->assertEquals(3, Sco_Array_Helper::seek($a = array(
			0,
			1,
			2,
			3,
			4,
			5), 3));
	}

	/**
	 * Generated from @assert (array(0, 1, 2, 3, 4, 5), 3) == 3.
	 *
	 * @covers Sco_Array_Helper::seek_key
	 */
	public function testSeek_key()
	{
		$this->assertEquals(0, Sco_Array_Helper::seek_key($a = array(
			"item1" => -1,
			"item2" => -1,
			"item3" => -1,
			"item4" => 0,
			"item5" => 2,
			"item6" => 2,
			"item7" => 1,
			), 'item4'));
	}

	/**
	 * Generated from @assert (array(0, 1, 2, 3, 4, 5), 3) == 3.
	 *
	 * @covers Sco_Array_Helper::seek_key
	 */
	public function testSeek_key2()
	{
		$a = array(
			"item1" => -1,
			"item2" => -1,
			"item3" => -1,
			"item4" => 0,
			"item5" => 2,
			"item6" => 2,
			"item7" => 1,
			);

		Sco_Array_Helper::seek_key($a, 'item4');

		$this->assertEquals('item4', key($a));
	}

	/**
	 * @covers Sco_Array_Helper::array_shuffle
	 * @todo Implement testArray_shuffle().
	 */
	public function testArray_shuffle()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @covers Sco_Array_Helper::is_assoc
	 * @todo Implement testIs_assoc().
	 */
	public function testIs_assoc()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @covers Sco_Array_Helper::is_array
	 * @todo Implement testIs_array().
	 */
	public function testIs_array()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @covers Sco_Array_Helper::array_unshift_assoc
	 * @todo Implement testArray_unshift_assoc().
	 */
	public function testArray_unshift_assoc()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @covers Sco_Array_Helper::array_push_assoc
	 * @todo Implement testArray_push_assoc().
	 */
	public function testArray_push_assoc()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @covers Sco_Array_Helper::array_remove_key
	 * @todo Implement testArray_remove_key().
	 */
	public function testArray_remove_key()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @covers Sco_Array_Helper::array_search_match
	 * @todo Implement testArray_search_match().
	 */
	public function testArray_search_match()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @covers Sco_Array_Helper::array_exchange
	 * @todo Implement testArray_exchange().
	 */
	public function testArray_exchange()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * @covers Sco_Array_Helper::recursive2array
	 * @todo Implement testRecursive2array().
	 */
	public function testRecursive2array()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

}


?>
