<?php

require_once dirname(__FILE__) . '/../../../../../Scorpio/Sco/Math/Format.php';

/**
 * Test class for Sco_Math_Format.
 * Generated by PHPUnit on 2012-06-29 at 11:04:56.
 */
class Sco_Math_FormatTest extends PHPUnit_Framework_TestCase
{

	/**
	 * @var Sco_Math_Format
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new Sco_Math_Format;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		
	}

	/**
	 * Generated from @assert ('1.2500000000') === '1.25'.
	 *
	 * @covers Sco_Math_Format::clean_decimal
	 */
	public function testClean_decimal()
	{
		$this->assertSame(
				'1.25'
				, $this->object->clean_decimal('1.2500000000')
		);
	}

	/**
	 * Generated from @assert ('1340959614.07259200') === '1340959614.072592'.
	 *
	 * @covers Sco_Math_Format::clean_decimal
	 */
	public function testClean_decimal2()
	{
		$this->assertSame(
				'1340959614.072592'
				, $this->object->clean_decimal('1340959614.07259200')
		);
	}

	/**
	 * @covers Sco_Math_Format::int
	 * @todo Implement testInt().
	 */
	public function testInt()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Sco_Math_Format::float
	 * @todo Implement testFloat().
	 */
	public function testFloat()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
