<?php

/**
 * Test class for Sco_Math_Format.
 * Generated by PHPUnit on 2012-06-29 at 11:04:56.
 */
class PHP_BugTest extends PHPUnit_Framework_TestCase
{

	/**
	 * my php 5.3.8 will fail return 1340959614.07259202
	 */
	public function testPrintfFloatWithString()
	{
		$this->assertSame(
				'1340959614.07259200'
				, sprintf('%0.8f', '1340959614.07259200')
		);
	}

}
