<?php

require_once dirname(__FILE__) . '/../../../../../../Scorpio/Sco/Math/Func/Distance.php';

/**
 * Test class for Sco_Math_Func_Distance.
 * Generated by PHPUnit on 2012-07-02 at 17:21:43.
 */
class Sco_Math_Func_DistanceTest extends PHPUnit_Framework_TestCase
{

	/**
	 * @var Sco_Math_Func_Distance
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new Sco_Math_Func_Distance;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		
	}

	/**
	 * Generated from @assert (10, 0) == 10.
	 *
	 * @covers Sco_Math_Func_Distance::ManhattanDistance
	 */
	public function testManhattanDistance()
	{
		$this->assertEquals(
				10
				, Sco_Math_Func_Distance::ManhattanDistance(10, 0)
		);
	}

	/**
	 * Generated from @assert (0, 10) == 10.
	 *
	 * @covers Sco_Math_Func_Distance::ManhattanDistance
	 */
	public function testManhattanDistance2()
	{
		$this->assertEquals(
				10
				, Sco_Math_Func_Distance::ManhattanDistance(0, 10)
		);
	}

	/**
	 * Generated from @assert (5, 5) == 10.
	 *
	 * @covers Sco_Math_Func_Distance::ManhattanDistance
	 */
	public function testManhattanDistance3()
	{
		$this->assertEquals(
				10
				, Sco_Math_Func_Distance::ManhattanDistance(5, 5)
		);
	}

	/**
	 * Generated from @assert (+0, +0) === false.
	 *
	 * @covers Sco_Math_Func_Distance::azimuth_compass
	 */
	public function testAzimuth_compass()
	{
		$this->assertSame(
				false
				, Sco_Math_Func_Distance::azimuth_compass(+0, +0)
		);
	}

	/**
	 * Generated from @assert (+0, +1) === 90.0.
	 *
	 * @covers Sco_Math_Func_Distance::azimuth_compass
	 */
	public function testAzimuth_compass2()
	{
		$this->assertSame(
				90.0
				, Sco_Math_Func_Distance::azimuth_compass(+0, +1)
		);
	}

	/**
	 * Generated from @assert (+1, +1) === 45.0.
	 *
	 * @covers Sco_Math_Func_Distance::azimuth_compass
	 */
	public function testAzimuth_compass3()
	{
		$this->assertSame(
				45.0
				, Sco_Math_Func_Distance::azimuth_compass(+1, +1)
		);
	}

	/**
	 * Generated from @assert (+1, +0) === 0.0.
	 *
	 * @covers Sco_Math_Func_Distance::azimuth_compass
	 */
	public function testAzimuth_compass4()
	{
		$this->assertSame(
				0.0
				, Sco_Math_Func_Distance::azimuth_compass(+1, +0)
		);
	}

	/**
	 * Generated from @assert (+0, -1) === -90.0.
	 *
	 * @covers Sco_Math_Func_Distance::azimuth_compass
	 */
	public function testAzimuth_compass5()
	{
		$this->assertSame(
				-90.0
				, Sco_Math_Func_Distance::azimuth_compass(+0, -1)
		);
	}

	/**
	 * Generated from @assert (-1, -1) === -135.0.
	 *
	 * @covers Sco_Math_Func_Distance::azimuth_compass
	 */
	public function testAzimuth_compass6()
	{
		$this->assertSame(
				-135.0
				, Sco_Math_Func_Distance::azimuth_compass(-1, -1)
		);
	}

	/**
	 * Generated from @assert (-1, +0) === 180.0.
	 *
	 * @covers Sco_Math_Func_Distance::azimuth_compass
	 */
	public function testAzimuth_compass7()
	{
		$this->assertSame(
				180.0
				, Sco_Math_Func_Distance::azimuth_compass(-1, +0)
		);
	}

	/**
	 * Generated from @assert (-1, -1) === -135.0.
	 *
	 * @covers Sco_Math_Func_Distance::azimuth_compass
	 */
	public function testAzimuth_compass8()
	{
		$this->assertSame(
				-135.0
				, Sco_Math_Func_Distance::azimuth_compass(-1, -1)
		);
	}

	/**
	 * Generated from @assert (5, 5) === 45.0.
	 *
	 * @covers Sco_Math_Func_Distance::azimuth_compass
	 */
	public function testAzimuth_compass9()
	{
		$this->assertSame(
				45.0
				, Sco_Math_Func_Distance::azimuth_compass(5, 5)
		);
	}

	/**
	 * Generated from @assert (-5, 5) === 135.0.
	 *
	 * @covers Sco_Math_Func_Distance::azimuth_compass
	 */
	public function testAzimuth_compass10()
	{
		$this->assertSame(
				135.0
				, Sco_Math_Func_Distance::azimuth_compass(-5, 5)
		);
	}

	/**
	 * Generated from @assert (5, -5) === -45.0.
	 *
	 * @covers Sco_Math_Func_Distance::azimuth_compass
	 */
	public function testAzimuth_compass11()
	{
		$this->assertSame(
				-45.0
				, Sco_Math_Func_Distance::azimuth_compass(5, -5)
		);
	}

	/**
	 * Generated from @assert (-5, -5) === -135.0.
	 *
	 * @covers Sco_Math_Func_Distance::azimuth_compass
	 */
	public function testAzimuth_compass12()
	{
		$this->assertSame(
				-135.0
				, Sco_Math_Func_Distance::azimuth_compass(-5, -5)
		);
	}

	/**
	 * Generated from @assert (5, 5, 0, 0, 1) === 45.0.
	 *
	 * @covers Sco_Math_Func_Distance::azimuth_compass
	 */
	public function testAzimuth_compass13()
	{
		$this->assertSame(
				45.0
				, Sco_Math_Func_Distance::azimuth_compass(5, 5, 0, 0, 1)
		);
	}

	/**
	 * Generated from @assert (-5, 5, 0, 0, 1) === 135.0.
	 *
	 * @covers Sco_Math_Func_Distance::azimuth_compass
	 */
	public function testAzimuth_compass14()
	{
		$this->assertSame(
				135.0
				, Sco_Math_Func_Distance::azimuth_compass(-5, 5, 0, 0, 1)
		);
	}

	/**
	 * Generated from @assert (5, -5, 0, 0, 1) === 315.0.
	 *
	 * @covers Sco_Math_Func_Distance::azimuth_compass
	 */
	public function testAzimuth_compass15()
	{
		$this->assertSame(
				315.0
				, Sco_Math_Func_Distance::azimuth_compass(5, -5, 0, 0, 1)
		);
	}

	/**
	 * Generated from @assert (-5, -5, 0, 0, 1) === 225.0.
	 *
	 * @covers Sco_Math_Func_Distance::azimuth_compass
	 */
	public function testAzimuth_compass16()
	{
		$this->assertSame(
				225.0
				, Sco_Math_Func_Distance::azimuth_compass(-5, -5, 0, 0, 1)
		);
	}

	/**
	 * Generated from @assert (+0, +0) === false.
	 *
	 * @covers Sco_Math_Func_Distance::azimuth_compass_2
	 */
	public function testAzimuth_compass_2()
	{
		$this->assertSame(
				false
				, Sco_Math_Func_Distance::azimuth_compass_2(+0, +0)
		);
	}

	/**
	 * Generated from @assert (+0, +1) === 0.0.
	 *
	 * @covers Sco_Math_Func_Distance::azimuth_compass_2
	 */
	public function testAzimuth_compass_22()
	{
		$this->assertSame(
				0.0
				, Sco_Math_Func_Distance::azimuth_compass_2(+0, +1)
		);
	}

	/**
	 * Generated from @assert (+1, +1) === 45.0.
	 *
	 * @covers Sco_Math_Func_Distance::azimuth_compass_2
	 */
	public function testAzimuth_compass_23()
	{
		$this->assertSame(
				45.0
				, Sco_Math_Func_Distance::azimuth_compass_2(+1, +1)
		);
	}

	/**
	 * Generated from @assert (+1, +0) === 90.0.
	 *
	 * @covers Sco_Math_Func_Distance::azimuth_compass_2
	 */
	public function testAzimuth_compass_24()
	{
		$this->assertSame(
				90.0
				, Sco_Math_Func_Distance::azimuth_compass_2(+1, +0)
		);
	}

	/**
	 * Generated from @assert (+0, -1) === 180.0.
	 *
	 * @covers Sco_Math_Func_Distance::azimuth_compass_2
	 */
	public function testAzimuth_compass_25()
	{
		$this->assertSame(
				180.0
				, Sco_Math_Func_Distance::azimuth_compass_2(+0, -1)
		);
	}

	/**
	 * Generated from @assert (-1, -1) === -135.0.
	 *
	 * @covers Sco_Math_Func_Distance::azimuth_compass_2
	 */
	public function testAzimuth_compass_26()
	{
		$this->assertSame(
				-135.0
				, Sco_Math_Func_Distance::azimuth_compass_2(-1, -1)
		);
	}

	/**
	 * Generated from @assert (-1, +0) === -90.0.
	 *
	 * @covers Sco_Math_Func_Distance::azimuth_compass_2
	 */
	public function testAzimuth_compass_27()
	{
		$this->assertSame(
				-90.0
				, Sco_Math_Func_Distance::azimuth_compass_2(-1, +0)
		);
	}

	/**
	 * Generated from @assert (-1, -1) === -135.0.
	 *
	 * @covers Sco_Math_Func_Distance::azimuth_compass_2
	 */
	public function testAzimuth_compass_28()
	{
		$this->assertSame(
				-135.0
				, Sco_Math_Func_Distance::azimuth_compass_2(-1, -1)
		);
	}

	/**
	 * Generated from @assert (0, 0) === ''.
	 *
	 * @covers Sco_Math_Func_Distance::polar
	 */
	public function testPolar()
	{
		$this->assertSame(
				''
				, Sco_Math_Func_Distance::polar(0, 0)
		);
	}

	/**
	 * Generated from @assert (0, 1) === 'N'.
	 *
	 * @covers Sco_Math_Func_Distance::polar
	 */
	public function testPolar2()
	{
		$this->assertSame(
				'N'
				, Sco_Math_Func_Distance::polar(0, 1)
		);
	}

	/**
	 * Generated from @assert (1, 0) === 'E'.
	 *
	 * @covers Sco_Math_Func_Distance::polar
	 */
	public function testPolar3()
	{
		$this->assertSame(
				'E'
				, Sco_Math_Func_Distance::polar(1, 0)
		);
	}

	/**
	 * Generated from @assert (0, -1) === 'S'.
	 *
	 * @covers Sco_Math_Func_Distance::polar
	 */
	public function testPolar4()
	{
		$this->assertSame(
				'S'
				, Sco_Math_Func_Distance::polar(0, -1)
		);
	}

	/**
	 * Generated from @assert (-1, 0) === 'W'.
	 *
	 * @covers Sco_Math_Func_Distance::polar
	 */
	public function testPolar5()
	{
		$this->assertSame(
				'W'
				, Sco_Math_Func_Distance::polar(-1, 0)
		);
	}

	/**
	 * Generated from @assert (1, 1) === 'NE'.
	 *
	 * @covers Sco_Math_Func_Distance::polar
	 */
	public function testPolar6()
	{
		$this->assertSame(
				'NE'
				, Sco_Math_Func_Distance::polar(1, 1)
		);
	}

	/**
	 * Generated from @assert (-1, 1) === 'NW'.
	 *
	 * @covers Sco_Math_Func_Distance::polar
	 */
	public function testPolar7()
	{
		$this->assertSame(
				'NW'
				, Sco_Math_Func_Distance::polar(-1, 1)
		);
	}

	/**
	 * Generated from @assert (1, -1) === 'SE'.
	 *
	 * @covers Sco_Math_Func_Distance::polar
	 */
	public function testPolar8()
	{
		$this->assertSame(
				'SE'
				, Sco_Math_Func_Distance::polar(1, -1)
		);
	}

	/**
	 * Generated from @assert (-1, -1) === 'SW'.
	 *
	 * @covers Sco_Math_Func_Distance::polar
	 */
	public function testPolar9()
	{
		$this->assertSame(
				'SW'
				, Sco_Math_Func_Distance::polar(-1, -1)
		);
	}

	/**
	 * Generated from @assert (0, 0) === ''.
	 *
	 * @covers Sco_Math_Func_Distance::polar_2
	 */
	public function testPolar_2()
	{
		$this->assertSame(
				''
				, Sco_Math_Func_Distance::polar_2(0, 0)
		);
	}

	/**
	 * Generated from @assert (0, 1) === 'N'.
	 *
	 * @covers Sco_Math_Func_Distance::polar_2
	 */
	public function testPolar_22()
	{
		$this->assertSame(
				'N'
				, Sco_Math_Func_Distance::polar_2(0, 1)
		);
	}

	/**
	 * Generated from @assert (1, 1) === 'NE'.
	 *
	 * @covers Sco_Math_Func_Distance::polar_2
	 */
	public function testPolar_23()
	{
		$this->assertSame(
				'NE'
				, Sco_Math_Func_Distance::polar_2(1, 1)
		);
	}

	/**
	 * Generated from @assert (1, 0) === 'E'.
	 *
	 * @covers Sco_Math_Func_Distance::polar_2
	 */
	public function testPolar_24()
	{
		$this->assertSame(
				'E'
				, Sco_Math_Func_Distance::polar_2(1, 0)
		);
	}

	/**
	 * Generated from @assert (0, -1) === 'S'.
	 *
	 * @covers Sco_Math_Func_Distance::polar_2
	 */
	public function testPolar_25()
	{
		$this->assertSame(
				'S'
				, Sco_Math_Func_Distance::polar_2(0, -1)
		);
	}

	/**
	 * Generated from @assert (-1, -1) === 'SW'.
	 *
	 * @covers Sco_Math_Func_Distance::polar_2
	 */
	public function testPolar_26()
	{
		$this->assertSame(
				'SW'
				, Sco_Math_Func_Distance::polar_2(-1, -1)
		);
	}

	/**
	 * Generated from @assert (-1, 0) === 'W'.
	 *
	 * @covers Sco_Math_Func_Distance::polar_2
	 */
	public function testPolar_27()
	{
		$this->assertSame(
				'W'
				, Sco_Math_Func_Distance::polar_2(-1, 0)
		);
	}

	/**
	 * Generated from @assert (-1, -1) === 'SW'.
	 *
	 * @covers Sco_Math_Func_Distance::polar_2
	 */
	public function testPolar_28()
	{
		$this->assertSame(
				'SW'
				, Sco_Math_Func_Distance::polar_2(-1, -1)
		);
	}

	/**
	 * @covers Sco_Math_Func_Distance::HexagonDistance
	 * @todo Implement testHexagonDistance().
	 */
	public function testHexagonDistance()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
